services:
  backend:
    build:
      context: .  # Ścieżka do katalogu z Dockerfile
      dockerfile: Dockerfile  
    container_name: backend-app
    depends_on:
      mysql:
        condition: service_healthy  # Czeka na zdrowy stan MySQL
    environment:
      DATABASE_URL: mysql+asyncmy://user:password@mysql:3306/smle-database
    ports:
      - "8000:8000"  # Port dla FastAPI lub innego serwera backendowego
    volumes:
      - ./backend:/app/backend  # Montowanie katalogu backendu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]  # Obsługa GPU
    command: ["python", "/app/backend/main.py"]  # Uruchamianie backendu

  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smle-database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./smle_database_dump.sql:/docker-entrypoint-initdb.d/smle_database_dump.sql  # Inicjalizacja bazy
      - mysql_data:/var/lib/mysql  # Trwałe przechowywanie danych MySQL
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  mysql_data:  # Definicja wolumenu dla MySQL