services:
  backend:
    build:
      context: .  # Ścieżka do katalogu z Dockerfile
      dockerfile: Dockerfile.backend
    container_name: backend-app
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql+asyncmy://user:password@mysql:3306/smle-database
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    command: ["python", "/app/backend/main.py"]

  maskrcnn:
    build:
      context: .
      dockerfile: Dockerfile.maskrcnn
    container_name: maskrcnn
    volumes:
      - ./backend/Mask_RCNN:/app/
      - ./backend/MCNN:/app/MCNN
      - ./backend/FasterRCNN:/app/FasterRCNN
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Kontener działa w trybie "na żądanie", nie uruchamiamy żadnego skryptu automatycznie
    command: ["tail", "-f", "/dev/null"]  # Utrzymuje kontener w stanie uruchomionym

  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smle-database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./smle_database_dump.sql:/docker-entrypoint-initdb.d/smle_database_dump.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  mysql_data: